### ISSUE TITLE
Reintegrate XML output

### ISSUE THREAD

**Issue by jonathansonntag** [discourse-lab/pocores#15]
<?xml version="1.0"?>
<!DOCTYPE root [
    <!ELEMENT root              (document+)>
    <!ELEMENT document          (text+, mentions*)>
        <!ATTLIST document computation_date CDATA #REQUIRED>
    <!ELEMENT text              (sentence+)>
    <!ELEMENT sentence          (token+)>
        <!ATTLIST sentence index CDATA #REQUIRED>
    <!ELEMENT token             (EMPTY)>
        <!ATTLIST token index   CDATA #REQUIRED>
        <!ATTLIST token head    CDATA #REQUIRED>
        <!ATTLIST token form    CDATA #REQUIRED>
        <!ATTLIST token lemma   CDATA #REQUIRED>
        <!ATTLIST token pos     CDATA #REQUIRED>
        <!ATTLIST token deprel  CDATA #REQUIRED>
        <!ATTLIST token num     CDATA #IMPLIED>
        <!ATTLIST token gen     CDATA #IMPLIED>
        <!ATTLIST token pers    CDATA #IMPLIED>
        <!ATTLIST token NE      CDATA #IMPLIED>
    <!ELEMENT mentions          (coreferring_set*)>
    <!ELEMENT coreferring_set   (mention+)>
        <!ATTLIST coreferring_set id  CDATA #REQUIRED>
    <!ELEMENT mention           (EMPTY)>
        <!ATTLIST mention start_token   CDATA #REQUIRED>
        <!ATTLIST mention end_token     CDATA #REQUIRED>
        <!ATTLIST mention surface_form  CDATA #REQUIRED>
        <!ATTLIST mention sentence_id   CDATA #REQUIRED>
]>

**Comment by arne-cl** [comment]
closed by @jonathansonntag with commit 1e2dd84da381a6e9ce34dd77937f191cbb9b0e53
